### ISSUE TITLE
How do you attach a VNC server to the running container?

### ISSUE THREAD

**Issue by vgoklani** [wk/docker-ib-tws#1]
Is there a simple way of connecting via VNC server?

I used this to get the IP address:

docker inspect --format '{{ .NetworkSettings.IPAddress }}' <CONTAINER>

and then opened a connection via vnc://ip:5900

but it refused to connect

**Comment by wk** [comment]
There is no support for VNC in this container. It is intended to be used with an X server present on the docker host, with X communication possible through a socket that is exported into the container.
